### ISSUE TITLE
Votetop and Lucky Vote

### ISSUE THREAD

**Issue by Builder45** [GeorgeV220/VoteRewards-5.2.2_SNAPSHOT#1]
Hello. Some months back I asked if it was possible to set the amount of people shown in the /vtop command. You said you would re-add it to the plugin, but after 4 months, it hasn't been added.
Just wanted to ask again, if you could please add this feature back 😄 

Also, it seems that the Lucky vote is broken. It doesn't really matter what value you put as the chance. It's always around 1%
(Ex. if I set it to 10. It's not 10% but still 1%. If I set it to 50, it's also around 1%). Not sure what's going on with that.

I'm using the latest official version: 3.3.6

**Comment by GeorgeV220** [comment]
Hey, sorry for the late respond i didn't get any notification about that.. i will add this feature on 4.0.. the new version will be released soon enough but it will be on alpha stage and then beta (again .-.) cause i don't have enough time for 100% testing

**Comment by GeorgeV220** [comment]
Please check the new prelease
https://github.com/GeorgeV220/VoteRewards/releases/tag/vPre-4.0
