### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by JavierPM87** [GeorgeV220/VoteRewards-5.2.2_SNAPSHOT#10]
**Describe the bug**
I see an alert on the console, what does it mean?

**Screenshots**
I have attached server log file

**Server Info (please complete the following information):**
I have the server hosted on a hosting called Scalacube
 - OS: [5.5.62-0ubuntu0.14.04.1 - (Ubuntu)]  I have obtained this information from PhpMyAdmin
 - Java Version [Java 11]
 - Minecraft Server [git-Paper-551 (MC: 1.16.5)]

**Additional context**
I also have the problem that people who vote do not receive rewards

[latest (2).log](https://github.com/GeorgeV220/VoteRewards/files/6386602/latest.2.log)

**Comment by GeorgeV220** [comment]
Hey,
thank you for your report. I will check it.

Please check your Votifier setup and VoteRewards config file!!

**Comment by GeorgeV220** [comment]
Hey,
Please try this version. (Enable load and save debug options in the config and also delete all VoteRewards userdata)

[VoteRewards-v4.7.1.0.zip](https://github.com/GeorgeV220/VoteRewards/files/6388596/VoteRewards-v4.7.1.0.zip)

**Comment by JavierPM87** [comment]
Hello George
It seems that there are problems, now the plugin does not load, I attach the log file


[latest.log](https://github.com/GeorgeV220/VoteRewards/files/6390674/latest.log)

**Comment by JavierPM87** [comment]
here another different error


[latest.log](https://github.com/GeorgeV220/VoteRewards/files/6390712/latest.log)

**Comment by GeorgeV220** [comment]
Problem solved and a version will be released with the new fixes/changes.
