### ISSUE TITLE
[BUG] Cannot disable Reminder

### ISSUE THREAD

**Issue by pokemonrocks9** [GeorgeV220/VoteRewards-5.2.2_SNAPSHOT#12]
**Describe the bug**
Reminder is still set to false and still reminding me in a shorter time than set

**To Reproduce**
Paper server running the latest version of VoteRewards

**Expected behavior**
Vote reminders disable or take longer

**Screenshots**

**Server Info (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04] Unknown Pebblehost
 - Java Version [e.g. OpenJDK 8] 16
 - Minecraft Server [e.g. 1.12.2] Paper 1.17.1 

**Additional context**

**Comment by GeorgeV220** [comment]
Hey, if you can please upload your config.yml (remove database credentials).

**Comment by pokemonrocks9** [comment]
[https://mcpaste.io/f1ddb6e9b5d66f27](url)
We raised the time from the default to make less annoying. Since we don't use sql no credentials needed

**Comment by GeorgeV220** [comment]
I have been trying for a while now to recreate the issue so that I can see what is wrong but it works for me without any problem. Could you give more info?

**Comment by GeorgeV220** [comment]
[voterewards-v5.1.0.zip](https://github.com/GeorgeV220/VoteRewards/files/7100086/voterewards-v5.1.0.zip)
Can you please try this jar ?? Thank you!!

**Comment by pokemonrocks9** [comment]
I shall try the jar this evening after work. To basically state it was giving a reminder every 2 minutes in spite of the reminder being off. We lengthened it largely to cause it to calm down.

**Comment by GeorgeV220** [comment]
120 seconds are the default value so it works (kinda hahaha). the switch is correctly coded so i can't see the problem.. probably i did something wrong but i can't find it yet and i can't reproduce the issue. don't worry tho i will find a solution!! ^-^

**Comment by pokemonrocks9** [comment]
Much appreciated. I'm sure it was something small and if the new version
fixes it I shall let you know

**Comment by GeorgeV220** [comment]
Hey, please verify if the new version fixes your issue!!

**Comment by pokemonrocks9** [comment]
Sorry for late reply. The issue seems fixed however the rewards aren't
being given to the right player who voted anymore, it seemed random who got
it.

**Comment by GeorgeV220** [comment]
try the latest release, please search on your userdata folder for duplicates. If you have duplicates, delete them.. sorry about that
