### ISSUE TITLE
Wiki Bug

### ISSUE THREAD

**Issue by Deveroonie** [GeorgeV220/VoteRewards-5.2.2_SNAPSHOT#14]
In the wiki, under softdepends, there is 2 of the same thing

    PlaceholderAPI
    MVdWPlaceholderAPI
    AuthMeReloaded
    WorldEdit or FastAsyncWorldEdit
    **PlaceholderAPI**

Why is there 2 of the same thing?

**Comment by GeorgeV220** [comment]
Thank you very much!! 
I had not noticed
