### ISSUE TITLE
[BUG] Error occurred while enabling plugin

### ISSUE THREAD

**Issue by prefislt** [GeorgeV220/VoteRewards-5.2.2_SNAPSHOT#15]
**Describe the bug**
Plugin errors out and doesn't work. 
Logs: [https://mclo.gs/xVVYujy](https://mclo.gs/xVVYujy)

**Server Info:**
 - Windows 11
 - Java 17 (Adoptium)
 - Minecraft 1.18.1 (Purpur build 1459)
 - VoteRewards v5.2.1

**Comment by GeorgeV220** [comment]
Hello,
Can you please try this jar?
[voterewards-5.2.1.zip](https://github.com/GeorgeV220/VoteRewards/files/7779979/voterewards-5.2.1.zip)

**Comment by prefislt** [comment]
Same errors.

**Comment by GeorgeV220** [comment]
Please send me the new error logs

**Comment by prefislt** [comment]
[https://mclo.gs/X0WqdFc](https://mclo.gs/X0WqdFc)
