### ISSUE TITLE
[BUG] Warn when player joins

### ISSUE THREAD

**Issue by Outlander87** [GeorgeV220/VoteRewards-5.2.2_SNAPSHOT#16]
**Describe the bug**
When a player joins the server this warn shows up

**To Reproduce**
Steps to reproduce the behavior: just join the server

**Expected behavior**
No warnings?

**Screenshots**

**Server Info (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04] ubuntu 20.04
 - Java Version [e.g. OpenJDK 8] amazon corretto 17
 - Minecraft Server [e.g. 1.12.2] paper 1.18.1 build 136

**Additional context**
https://pastebin.com/Lq5xfwhi

**Comment by GeorgeV220** [comment]
Hello, probably the same problem with #15, I need to check OptionUtils file. Except a fix tomorrow!!

**Comment by GeorgeV220** [comment]
Hello,
Can you please try this test build ?
[voterewards-5.2.1.zip](https://github.com/GeorgeV220/VoteRewards/files/7835342/voterewards-5.2.1.zip)
