### ISSUE TITLE
Votetop footer and placeholders.

### ISSUE THREAD

**Issue by RealBarthold** [GeorgeV220/VoteRewards-5.2.2_SNAPSHOT#4]
I know it's holidays atm, so if you see this. Feel free to ignore it and relax during the holidays for now 😄 

I really like the new features in the 4.x updates. The hologram addition is pretty awesome!
And it's good to see that the amount of top voters can be customized now.

**Votetop footer**
I'm having some issues trying to disable the votetop footer. I tried making it empty or putting [] in the config.
The first attempt resulted in an empty line and the second attempt resulted in a NULL error.
I would love to see a way to disable it in the future.

**Placeholders**
Then there's the placeholders:
`voterewards_total_votes
voterewards_votes_needed
voterewards_votes_until
voterewards_player_votes
voterewards_top_voter`

They seem to be pretty broken atm. _total_votes_ and _player_votes_ returns 0 for me, no matter how many votes a person has. _top_voter_ seems to be the only one working. And I'm not even sure what _votes_needed_ and _votes_until_ are supposed to do. Are they related to cumulative voting? vote parties? 
I would really like to use placeholders elsewhere. So I would also love to see this fixed in the future as well.

Thank you for your work on this plugin and happy holidays!

**Comment by GeorgeV220** [comment]
Hey,
I added 2 options in the config to disable the header and footer of votetop. Try the new version 4.1.3
Please update your config values
```yaml
  votetop: 5
```
to
```yaml
  votetop:
    header: true
    footer: true
    voters: 5
```

Also please contact me on Discord GeorgeV22#3200 to check your placeholder issues cause for me is working just fine. Probably i did something wrong but i can't tell without testing and etc.

Thank you and happy holidays!!

**Comment by RealBarthold** [comment]
I downloaded the new version and tried out the new config option. It works like a charm! Thank you very much!

Also got some additional info on placeholders from the developer:

"voterewards_votes_needed" and "voterewards_votes_until" are related to Vote Parties.

If anyone has trouble with the "voterewards_player_votes" placeholder, you just need to change it to:
"voterewards_player_player_votes" instead. Then it will work properly. (But it will be changed to voterewards_player_votes in the near future)

Thanks again to you George, for the good support!
