### ISSUE TITLE
Daily Votes (ex: [BUG] (Solved) Could not pass VotifierEvent to VoteRewards v4.3.2)

### ISSUE THREAD

**Issue by DarkKingKaan** [GeorgeV220/VoteRewards-5.2.2_SNAPSHOT#5]
**Describe the bug**
An error occurs when VotingPlugin sends an event to VoteRewards on 1.16.5

**To Reproduce**
Run a 1.16.5 PaperMC Minecraft server, set the plugin up, and do /fakevote. Items are received, but there are no "thanks for voting" message. There's an error in the console.

**Expected behavior**
I expected it to print the correct message and not throw out an error.

**Screenshots**
https://i.imgur.com/Kzq5EtY.png
https://i.imgur.com/RdGUOLR.png

**Server Info (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]  Latest Ubuntu
 - Java Version [e.g. OpenJDK 8]  Java 11
 - Minecraft Server [e.g. 1.12.2]  1.16.5 PaperMC

**Additional context**
There's nothing to add. Thank you in advance for your help.

**Comment by GeorgeV220** [comment]
Hello,
can you please post your config.yml ?

**Comment by DarkKingKaan** [comment]
Sure, here you go.
There is a slight chance that I screwed something up in there.
Thank you in advance for your help.

[config.zip](https://github.com/GeorgeV220/VoteRewards/files/5894958/config.zip)

**Comment by GeorgeV220** [comment]
Hey,
A lot of sections in Rewards section are missing. The problem is that you have enabled cumulative voting without having cumulative section on rewards section. Check default config from here:
 https://github.com/GeorgeV220/VoteRewards/blob/master/src/main/resources/config.yml

**Comment by DarkKingKaan** [comment]
Alright, that was the problem. It's fixed now.
Before closing - is there a way to see how many votes are left for the "daily" reward? Just like cumulative votes that say "X votes until next reward" when using /vote.

Thank you for your help!

**Comment by GeorgeV220** [comment]
Daily rewards are still under development. keep this issue open to let you know when it is 100% ready

**Comment by DarkKingKaan** [comment]
Okay, I will. Looking forward, Thanks. :)

**Comment by GeorgeV220** [comment]
Hey,
sorry for the late respond, Please try the latest build!!
