### ISSUE TITLE
Adding vote sites

### ISSUE THREAD

**Issue by ProGitHubUser** [GeorgeV220/VoteRewards-5.2.2_SNAPSHOT#6]
Please excuse me if this a dumb issue but I can't figure out how exactly to add a vote site. Any help? thank you

**Comment by GeorgeV220** [comment]
Hey,
you need to setup Votifier (to listen for votes from voting sites). If you want to add the sites on ./votes just edit messages.yml
If you need help with the setup add me on discord and i'll help you when i have time
GeorgeV22#3200
